create extension if not exists pgcrypto;

do $$
begin
    if not exists (select 1 from pg_type where typname = 'attendance_status_enum') then
        create type attendance_status_enum as enum ('Pending', 'Present', 'Absent');
    end if;
end $$;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    full_name varchar(100) not null,
    email varchar(100) not null unique,
    password varchar(255) not null,
    remember_token varchar(100),
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

create table if not exists public.events (
    id bigint generated by default as identity primary key,
    event_name varchar(100) not null,
    description text,
    event_date date not null,
    start_time time without time zone,
    end_time time without time zone,
    venue varchar(150) not null,
    max_slots integer not null check (max_slots > 0),
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

create table if not exists public.registrations (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(100) not null,
    contact_number varchar(11) not null,
    attendance_status attendance_status_enum not null default 'Pending',
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    constraint registrations_event_email_unique unique (event_id, email),
    constraint registrations_contact_number_digits check (contact_number ~ '^[0-9]{11}$')
);

create index if not exists idx_events_event_date on public.events(event_date);
create index if not exists idx_registrations_event_id on public.registrations(event_id);
create index if not exists idx_registrations_attendance_status on public.registrations(attendance_status);

create or replace view public.v_dashboard_stats as
select
    (select count(*) from public.events) as total_events,
    (select count(*) from public.registrations) as total_registrations,
    (
        select count(*)
        from public.events e
        where (
            select count(*)
            from public.registrations r
            where r.event_id = e.id
        ) >= e.max_slots
    ) as full_events,
    (
        select count(*)
        from public.events
        where event_date >= current_date
    ) as upcoming_events;
