-- =====================================================================
-- EventLink Complete Supabase Schema
-- Updated: April 29, 2026
-- Copy and paste this entire file into Supabase SQL Editor
-- =====================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =====================================================================
-- ENUMS
-- =====================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendance_status_enum') THEN
        CREATE TYPE attendance_status_enum AS ENUM ('Pending', 'Present', 'Absent');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role_enum') THEN
        CREATE TYPE user_role_enum AS ENUM ('admin', 'attendee');
    END IF;
END $$;

-- =====================================================================
-- USERS TABLE (Updated with contact_number and role)
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    contact_number VARCHAR(11) UNIQUE,
    role user_role_enum NOT NULL DEFAULT 'attendee',
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

-- Create indexes for users table
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);
CREATE INDEX IF NOT EXISTS idx_users_contact_number ON public.users(contact_number);

-- =====================================================================
-- EVENTS TABLE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(100) NOT NULL,
    description TEXT,
    event_date DATE NOT NULL,
    start_time TIME WITHOUT TIME ZONE,
    end_time TIME WITHOUT TIME ZONE,
    venue VARCHAR(150) NOT NULL,
    max_slots INTEGER NOT NULL CHECK (max_slots > 0),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

-- Create indexes for events table
CREATE INDEX IF NOT EXISTS idx_events_event_date ON public.events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_event_name ON public.events(event_name);

-- =====================================================================
-- REGISTRATIONS TABLE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.registrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    contact_number VARCHAR(11) NOT NULL,
    attendance_status attendance_status_enum NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT registrations_event_email_unique UNIQUE (event_id, email),
    CONSTRAINT registrations_contact_number_digits CHECK (contact_number ~ '^[0-9]{11}$')
);

-- Create indexes for registrations table
CREATE INDEX IF NOT EXISTS idx_registrations_event_id ON public.registrations(event_id);
CREATE INDEX IF NOT EXISTS idx_registrations_email ON public.registrations(email);
CREATE INDEX IF NOT EXISTS idx_registrations_attendance_status ON public.registrations(attendance_status);
CREATE INDEX IF NOT EXISTS idx_registrations_created_at ON public.registrations(created_at DESC);

-- =====================================================================
-- VIEWS
-- =====================================================================

CREATE OR REPLACE VIEW public.v_dashboard_stats AS
SELECT
    (SELECT COUNT(*) FROM public.events) AS total_events,
    (SELECT COUNT(*) FROM public.registrations) AS total_registrations,
    (
        SELECT COUNT(*)
        FROM public.events e
        WHERE (
            SELECT COUNT(*)
            FROM public.registrations r
            WHERE r.event_id = e.id
        ) >= e.max_slots
    ) AS full_events,
    (
        SELECT COUNT(*)
        FROM public.events
        WHERE event_date >= CURRENT_DATE
    ) AS upcoming_events;

-- =====================================================================
-- SAMPLE DATA (Optional - uncomment to seed)
-- =====================================================================

-- Insert admin user (username: admin, password: password123)
INSERT INTO public.users (username, full_name, email, contact_number, role, password, created_at, updated_at)
VALUES (
    'admin',
    'EveLink Administrator',
    'admin@evelink.local',
    NULL,
    'admin',
    '$2y$12$9y3KxXvmQ0K3ZG5Z8KvH6e1F3XjZ7X6Z7X6Z7X6Z7X6Z7X6Z7X6Z6', -- password123 hashed
    NOW(),
    NOW()
)
ON CONFLICT (email) DO UPDATE SET
    updated_at = NOW(),
    role = 'admin',
    password = '$2y$12$9y3KxXvmQ0K3ZG5Z8KvH6e1F3XjZ7X6Z7X6Z7X6Z7X6Z7X6Z7X6Z6';

-- =====================================================================
-- ROW LEVEL SECURITY (Optional - if enabling RLS)
-- =====================================================================

-- Uncomment and modify these if you want to enable Row Level Security
-- ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

-- =====================================================================
-- NOTES
-- =====================================================================
-- 
-- Column Specifications:
-- 
-- USERS TABLE:
--   - id: Primary key, auto-incrementing bigint
--   - username: 50 char max, unique, alphanumeric + underscore
--   - full_name: 100 char max, user's full name
--   - email: 100 char max, unique email address
--   - contact_number: 11 char max (nullable), unique, Philippine phone format (09XXXXXXXXX)
--   - role: 'admin' or 'attendee' (default: 'attendee')
--   - password: 255 char max, bcrypt hashed
--   - remember_token: 100 char max, for "remember me" functionality
--   - created_at: Timestamp when record was created
--   - updated_at: Timestamp when record was last updated
--
-- EVENTS TABLE:
--   - id: Primary key, auto-incrementing bigint
--   - event_name: 100 char max, required event name
--   - description: Long text field for event details
--   - event_date: Date when event occurs
--   - start_time: Time when event starts
--   - end_time: Time when event ends
--   - venue: 150 char max, event location/venue
--   - max_slots: Integer, maximum registration capacity (must be > 0)
--   - created_at: Timestamp when record was created
--   - updated_at: Timestamp when record was last updated
--
-- REGISTRATIONS TABLE:
--   - id: Primary key, auto-incrementing bigint
--   - event_id: Foreign key to events table (cascade delete)
--   - first_name: 50 char max, attendee first name
--   - last_name: 50 char max, attendee last name
--   - email: 100 char max, attendee email
--   - contact_number: 11 char max, phone number (digits only)
--   - attendance_status: 'Pending', 'Present', or 'Absent' (default: 'Pending')
--   - created_at: Timestamp when record was created
--   - updated_at: Timestamp when record was last updated
--
-- UNIQUE CONSTRAINTS:
--   - users.username: No duplicate usernames
--   - users.email: No duplicate emails
--   - users.contact_number: No duplicate phone numbers
--   - registrations(event_id, email): No duplicate registrations per event
--
-- =====================================================================
-- TROUBLESHOOTING
-- =====================================================================
--
-- If you get an error about existing types/tables:
--   1. These are handled with "IF NOT EXISTS" or "ON CONFLICT" clauses
--   2. You can drop and recreate if needed:
--      DROP TABLE IF EXISTS public.registrations CASCADE;
--      DROP TABLE IF EXISTS public.events CASCADE;
--      DROP TABLE IF EXISTS public.users CASCADE;
--      DROP TYPE IF EXISTS attendance_status_enum CASCADE;
--      DROP TYPE IF EXISTS user_role_enum CASCADE;
--
-- Then re-run this entire schema.
--
-- =====================================================================
